In [6]:
import numpy as np

In [2]:
#1.Genera un array bidimensional de 4 x 3 con valores aleatorios enteros entre el 34 y el 98. Una vez creado cada array comprueba las dimensiones y los tipos de datos que tenemos en el array.

array_1 = np.random.randint(34, 99, (4,3))
print(array_1)

[[94 74 94]
 [74 41 79]
 [40 57 66]
 [92 34 97]]


In [3]:
array_1.dtype

dtype('int32')

In [4]:
#2 Crea dos arrays (unidimensional, bidimensional) usando el método np.array().

lista1 = [34,56,71,98, 10]
lista2 = [[23,45,89, 56], [12,43,82,44]]

array_lista1 = np.array(lista1) 
array_lista2 = np.array(lista2) 


In [5]:
print(array_lista1)



[34 56 71 98 10]


In [6]:
print(array_lista2)

[[23 45 89 56]
 [12 43 82 44]]


#3 Crea un array unidimensional con 50 elementos con el método que prefieras y extrae:


In [7]:
array_q3 = np.random.randint(1, 100, 50)


In [8]:
print(array_q3)

[63 59 52 82 37 72  8 13  7 27  9 45 27 66 31 73 56 88 19  6 26 33 23 23
 39 19 59 59 53 68 85 72 65 67 17 22 61  4 65 42 19 68 79 61 54 24 47 78
 14 58]


In [9]:
#El primer elemento.

array_q3[0]

np.int32(63)

In [10]:
#Lo elementos que están en posición impar.

array_q3[1::2]

array([59, 82, 72, 13, 27, 45, 66, 73, 88,  6, 33, 23, 19, 59, 68, 72, 67,
       22,  4, 42, 68, 61, 24, 78, 58], dtype=int32)

In [11]:
#Los cuatro primeros elementos.

array_q3[0:4:]

array([63, 59, 52, 82], dtype=int32)

In [12]:
#Los últimos tres elementos.
array_q3[-3::]

array([78, 14, 58], dtype=int32)

In [13]:
#Los elementos entre el 4 y el 8 (incluido).
array_q3[3:8:]

array([82, 37, 72,  8, 13], dtype=int32)

In [14]:
#Crea un array de dos dimensiones de 4 x 5 con el método que prefieras y extrae:

array_q4 = np.random.randint(1, 100, (2, 4, 5))

In [15]:
print(array_q4)

[[[58 22 80 97 55]
  [58  3 78  1 15]
  [26  4 40 32  8]
  [41 60 48 30 65]]

 [[ 4 26 97 14  8]
  [69 60 27 35 58]
  [63 19 24 66 34]
  [66  9 61 69 16]]]


In [33]:
#La primera fila y todas las columnas.
print(array_q4[0,0])

[58 22 80 97 55]


In [36]:
#filas pares

print(array_q4[:,::2])


[[[58 22 80 97 55]
  [26  4 40 32  8]]

 [[ 4 26 97 14  8]
  [63 19 24 66 34]]]


In [37]:
#La primera columna y todas las filas.
print(array_q4[:,::, 0:1:])

[[[58]
  [58]
  [26]
  [41]]

 [[ 4]
  [69]
  [63]
  [66]]]


In [14]:
#5Crea un array bidimensional con 20 elementos aleatrorios entre 0 y 50 con el método que prefieras y:

array_q5 = np.random.randint(0, 50, size=(4, 5))

In [15]:
array_q5

array([[ 5, 32,  9, 48, 29],
       [49, 12, 11, 24, 47],
       [35, 15, 11, 18, 37],
       [40, 23, 28,  1, 28]], dtype=int32)

In [63]:
#Crea una mascara o filtro donde los valores mayores a 30 y menores a 10 se reemplace por "objetivo" y el resto por "no es mi objetivo".

#valores > 30 :'objetivo'
#valores < 10 : 'no es mi objetivo'

mask_greater_than_30 = array_q5 > 30
mask_less_than_10 = array_q5 < 10




In [56]:
datos_mayor_30 = array_q5[array_q5 > 30]
print(datos_mayor_30)

[36 38 46 34 41]


In [64]:
# Use np.where() to replace values that match the condition with 'objectivo'
array_obj = array_q5.astype(object)  # Convert to object type to support string replacement

# Replace values that match the condition
result = np.where(mask_greater_than_30, 'objetivo', array_obj), np.where(mask_less_than_10, 'no es el objetivo', array_obj), 

# Print the resulting array
print("Array after replacement:")
print(result)

Array after replacement:
(array([23, 12, 15, 9, 'objetivo', 25, 'objetivo', 1, 25, 5, 21, 3, 7,
       'objetivo', 5, 11, 'objetivo', 'objetivo', 1, 7], dtype=object), array([23, 12, 15, 'no es el objetivo', 36, 25, 38, 'no es el objetivo',
       25, 'no es el objetivo', 21, 'no es el objetivo',
       'no es el objetivo', 46, 'no es el objetivo', 11, 34, 41,
       'no es el objetivo', 'no es el objetivo'], dtype=object))


In [67]:
#Los valores de mi array bidimensional multiplicalos por el escalar 10.
escalar = 10

multiplicacion_escalar = array_q5 * escalar
multiplicacion_escalar

array([230, 120, 150,  90, 360, 250, 380,  10, 250,  50, 210,  30,  70,
       460,  50, 110, 340, 410,  10,  70], dtype=int32)

In [7]:
#6 Crea un nuevo array de dos dimensiones con la misma forma que el anterior y con el método que prefieras y realiza lo siguiente:

array_q6 = np.random.randint(0, 50, size=(4, 5))


In [16]:
print(array_q5)
print(array_q6)

[[ 5 32  9 48 29]
 [49 12 11 24 47]
 [35 15 11 18 37]
 [40 23 28  1 28]]
[[29  9 17 12 23]
 [36 36 27  3 22]
 [ 2 27  1 28 20]
 [45 12 42 30 14]]


In [17]:
#Suma el primer array con el segundo.
suma = array_q5 + array_q6

suma

array([[34, 41, 26, 60, 52],
       [85, 48, 38, 27, 69],
       [37, 42, 12, 46, 57],
       [85, 35, 70, 31, 42]], dtype=int32)

In [19]:
#Aplicar la potencia para el primer array elevado al segundo.

print(array_q5)

potencia = np.power(array_q5, 2)

print(potencia)

[[ 5 32  9 48 29]
 [49 12 11 24 47]
 [35 15 11 18 37]
 [40 23 28  1 28]]
[[  25 1024   81 2304  841]
 [2401  144  121  576 2209]
 [1225  225  121  324 1369]
 [1600  529  784    1  784]]


In [24]:

#7 Crea un array, puede ser bidimensional! Eso si, los valores tienen que estar entre 0-100

array_q7 = np.random.randint(0,100, (4,5))

array_q7


array([[89, 79, 74, 20, 85],
       [49, 39, 91, 73, 16],
       [43, 96, 91, 73, 81],
       [22, 11, 71, 44, 21]], dtype=int32)

In [26]:
#La media de los elementos

media = np.mean(array_q7)

media


np.float64(58.4)

In [29]:
#La media de las columnas y redondéalo a dos decimales

media_columnas = np.mean(array_q7, axis = 0)

media_columnas = np.round(media_columnas, 2)

media_columnas



array([50.75, 56.25, 81.75, 52.5 , 50.75])

In [31]:
#El valor máximo de cada fila

valor_max = np.max(array_q7, axis = 1)

valor_max

array([89, 91, 96, 71], dtype=int32)

In [33]:
#El valor mínimo de cada fila

valor_min = np.min(array_q7, axis = 1)

valor_min

array([20, 16, 43, 11], dtype=int32)

In [34]:
#Hay algun valor que sea mayor que 90 en tu array

datos_mayor_90 = array_q7[array_q7 > 90]
print(datos_mayor_90)

[91 96 91]


In [36]:
#Donde los podemos encontrar, cuáles son sus índices

indexes = np.where(array_q7 > 90)

indexes

(array([1, 2, 2]), array([2, 1, 2]))

In [38]:
#Ordena el array de mayor a menor

array_q7_sorted= np.sort(array_q7)

array_q7_sorted

array([[20, 74, 79, 85, 89],
       [16, 39, 49, 73, 91],
       [43, 73, 81, 91, 96],
       [11, 21, 22, 44, 71]], dtype=int32)