In [1]:
import numpy as np
import pandas as pd

In [2]:
# Crea un array de dos dimensiones con 4 filas y 3 columnas.
array_q1 = np.random.randint(1,50, (4,3)) 
print(array_q1)

[[ 2 10 42]
 [28 22 39]
 [32 36 48]
 [15 27 33]]


In [3]:
# Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".
df_q1 = pd.DataFrame(array_q1)
index_col = ['España', 'Francia', 'Italia']
df_q1

0   1   2
0   2  10  42
1  28  22  39
2  32  36  48
3  15  27  33

In [4]:
df_q1 = df_q1.rename(columns={0: "España", 1: "Francia", 2: "Italia"})
df_q1


España  Francia  Italia
0       2       10      42
1      28       22      39
2      32       36      48
3      15       27      33

In [6]:
df_medallas = pd.read_csv('medallas.csv')

In [7]:
df_medallas

Unnamed: 0             País   Oro  Plata  Bronce
0           1            China  1473    994     720
1           2            Japón  1032   1037     985
2           3    Corea del Sur   745    663     827
3           4             Irán   179    181     197
4           5       Kazajistán   155    158     224
5           6            India   154    202     315
6           7        Tailandia   132    175     278
7           8        Indonesia   112    131     240
8           9     China Taipéi    99    144     276
9          10  Corea del Norte    91    120     235

In [8]:
#Crea una nueva columma que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.

df_medallas['total'] = df_medallas['Oro'] + df_medallas['Plata'] + df_medallas['Bronce']

In [9]:
df_medallas

Unnamed: 0             País   Oro  Plata  Bronce  total
0           1            China  1473    994     720   3187
1           2            Japón  1032   1037     985   3054
2           3    Corea del Sur   745    663     827   2235
3           4             Irán   179    181     197    557
4           5       Kazajistán   155    158     224    537
5           6            India   154    202     315    671
6           7        Tailandia   132    175     278    585
7           8        Indonesia   112    131     240    483
8           9     China Taipéi    99    144     276    519
9          10  Corea del Norte    91    120     235    446

In [ ]:
A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la 

In [15]:
import random

#Crea dos listas:
#Una que se llame "valores" que tenga 7 números aleatorios
#Otra que se llame "indices" que tenga 7 strings que se llamen como los días de la semana.

valores = [random.randint(1, 100) for _ in range(7)]  # Random numbers from 1 to 100
valores





[31, 33, 19, 66, 95, 78, 70]

In [16]:
indices = ['Mon', 'Tues', 'Weds', 'Thurs', 'Fri', 'Sat', 'Sun']
indices

['Mon', 'Tues', 'Weds', 'Thurs', 'Fri', 'Sat', 'Sun']

In [17]:
#A partir de estas dos listas crea una Serie donde la variable "valores" sean los valores de la Serie 
# y la variable indices sean los índices de la Serie.

serie = pd.Series(valores, indices)
serie

Mon      31
Tues     33
Weds     19
Thurs    66
Fri      95
Sat      78
Sun      70
dtype: int64

In [ ]:
#A partir de las dos listas anteriores crea un diccionario usando un bucle for. 
# Para hacer esto tenemos el método zip que nos permite iterar por dos listas a la vez. 

In [18]:
dictionary = {}

for indices, valores in zip(indices, valores):
    dictionary[indices] = valores

print(dictionary)

{'Mon': 31, 'Tues': 33, 'Weds': 19, 'Thurs': 66, 'Fri': 95, 'Sat': 78, 'Sun': 70}


In [21]:
serie_dict = pd.Series(dictionary)

In [24]:
#¿Qué forma tiene esta última Serie?
#¿Qué tipo de datos tiene?
#¿Qué tamaño tiene?
#¿Cuáles son los índices de la Serie?
#¿Y los values?

print(serie_dict)
print(serie_dict.shape)
print(serie_dict.dtype)
print(serie_dict.size)
print(serie_dict.size)
print(serie_dict.index)
print(serie_dict.values)


Mon      31
Tues     33
Weds     19
Thurs    66
Fri      95
Sat      78
Sun      70
dtype: int64
(7,)
int64
7
7
Index(['Mon', 'Tues', 'Weds', 'Thurs', 'Fri', 'Sat', 'Sun'], dtype='object')
[31 33 19 66 95 78 70]


In [26]:
#Extrae el valor para el índice "lunes"

print(serie_dict.loc['Mon'])

31


In [36]:
#Extrae el valor para el índice "lunes", "martes" y "miércoles".
serie_dict.loc['Mon':'Weds']

Mon     31
Tues    33
Weds    19
dtype: int64

In [38]:
#Extrae el valor para el índice "lunes" y "domingo".

serie_dict.iloc[0:2]

Mon     31
Tues    33
dtype: int64